### ISSUE TITLE
Dependency on NI Vision Module

### ISSUE THREAD

**Issue by rbenji23** [NIVeriStandAdd-Ons/FPGA-Custom-Device#5] opened 2018-08-30 15:55 UTC
The load help file.vi has a dependency on the Load CHM file.vi which is only included in the NI vision module.

**Comment by tannerblair** [comment] 2018-11-09 16:51
This is caused by you missing a dependency -- likely the https://github.com/NIVeriStandAdd-Ons/HTML-Help-File-Tools. Because this is a 3rd-party package, it shows up as Vision Module. That part is a known NI bug, not a FPGA Addon bug.

I'm closing this, but I've created #6.

**Closed as completed by tannerblair** 2018-11-09 16:51 UTC
